sudo: required
language: elixir
elixir:
  - 1.11
opt_release:
  - 23.0

addons:
  postgres: "9.4"

sservices:
  - postgresql
  - docker

cache:
  directories:
    - _build
    - deps
before_script:  
  - mix local.hex --force  
  - mix local.rebar --force  
  - mix do deps.get, deps.compile
script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)